# Generated by Django 3.1.1 on 2020-10-04 13:15

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(default=profiles.models.UserProfile, max_length=200),
        ),
    ]
