# Generated by Django 3.1.1 on 2020-10-04 14:44

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicado', '0002_auto_20201004_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='email',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=200),
        ),
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=200),
        ),
    ]
