# Generated by Django 3.1.1 on 2020-10-04 15:02

import checkout.models
import django.contrib.auth.models
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicado', '0003_auto_20201004_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='nick',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=200),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='forum',
            name='email',
            field=models.CharField(default=checkout.models.Order, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(default=profiles.models.UserProfile, max_length=200),
        ),
    ]
