# Generated by Django 3.1.1 on 2020-10-19 20:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comunicado', '0005_auto_20201008_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='nick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=200),
        ),
    ]
