# Generated by Django 3.1.1 on 2020-10-19 22:25

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comunicado', '0007_auto_20201019_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forum',
            name='email',
            field=models.EmailField(default=django.contrib.auth.models.User, max_length=200),
        ),
    ]
