# Generated by Django 3.1.1 on 2020-10-19 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comunicado', '0008_auto_20201019_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
