# Generated by Django 3.1.1 on 2020-10-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201021_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_manager',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_team',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
