# Generated by Django 3.1.1 on 2020-10-23 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201021_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_company',
            new_name='company',
        ),
    ]
