# Generated by Django 3.1.1 on 2020-10-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_manager',
            field=models.BooleanField(default=True),
        ),
    ]
