# Generated by Django 3.1.1 on 2020-10-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_manager',
        ),
    ]
