# Generated by Django 3.1.1 on 2020-10-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_remove_order_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company_name',
        ),
    ]
