# Generated by Django 3.1.1 on 2020-10-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
